name: reactor_wallet
description: A Solana mobile wallet

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  solana: ^0.17.2
  google_fonts: ^2.1.0
  bip39: ^1.0.6
  worker_manager: ^4.2.3
  url_launcher: ^6.0.12
  cached_network_image: ^3.2.0
  encrypt: ^5.0.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  qr_code_scanner: ^0.6.1
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^1.0.4
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  msix: ^2.8.12

flutter:
  uses-material-design: true
  assets:
    - assets/

msix_config:
  display_name: Reactor Wallet
  publisher_display_name: Marc Espín Sanz
  identity_name: MarcEspinSanz.Reactor.Wallet
  msix_version: 0.1.0.1
  logo_path: ./windows/runner/resources/app_icon.ico
  capabilities: "internetClient"