name: solana_wallet
description: A solana mobile wallet

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  solana: 
    git: 
      url: git://github.com/cryptoplease/cryptoplease-dart.git
      path: packages/solana
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  tuple: ^2.0.0
  google_fonts: ^2.1.0
  bip39: ^1.0.6
  worker_manager: ^4.2.3
  url_launcher: ^6.0.12
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
