name: solana_wallet
description: A solana mobile wallet

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  solana: 
    git: 
      url: git://github.com/cryptoplease/cryptoplease-dart.git
      path: packages/solana
  google_fonts: ^2.1.0
  bip39: ^1.0.6
  worker_manager: ^4.2.3
  url_launcher: ^6.0.12
  cached_network_image: ^3.2.0
  encrypt: ^5.0.1
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0-dev.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shimmer: ^2.0.0
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
